### ISSUE TITLE
Composer .bin

### ISSUE THREAD

**Issue by lolos** [victorjonsson/PHP-Benchmark#1]
I'm trying to install version 1.1.3 and I get the response on Composer:

`Skipped installation of bin ./php-benchmark for package phpbenchmark/phpbenchmark: file not found in package`

and it generates the fatal error in code:

`syntax error, unexpected 'class' (T_CLASS), expecting identifier (T_STRING) or variable (T_VARIABLE) or '{' or '$' in /vendor/phpbenchmark/phpbenchmark/lib/PHPBenchmark/testing/metrics/PerformanceInfo.php:165`

**Comment by victorjonsson** [comment]
Try 1.1.4 out

**Comment by victorjonsson** [comment]
The php-error means that you dont have php version >= 5.5.0
